In [1]:
print("Hello, Data Science!")

Hello, Data Science!

In [2]:
import pandas as pd

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("Manchester.csv")

In [5]:
df.head()

,Unnamed: 0,id,price,bedrooms,bathrooms,sqft_living,sqft_total,floors,waterfront,view,condition,grade,built,renovated,living_area
0,0,7129300520,221900,3.0,1.00,1180,5650,1.0,0,0,3,7,1955,0,1340
1,1,6414100192,538000,3.0,2.25,2570,7242,2.0,0,0,3,7,1951,1991,1690
2,2,5631500400,180000,2.0,1.00,770,10000,1.0,0,0,3,6,1933,0,2720
3,3,2487200875,604000,4.0,3.00,1960,5000,1.0,0,0,5,7,1965,0,1360
4,4,1954400510,510000,3.0,2.00,1680,8080,1.0,0,0,3,8,1987,0,1800

In [6]:
df.shape

(19999, 15)

In [7]:
df.isnull().sum()

Unnamed: 0      0
id              0
price           0
bedrooms       13
bathrooms      10
sqft_living     0
sqft_total      0
floors          0
waterfront      0
view            0
condition       0
grade           0
built           0
renovated       0
living_area     0
dtype: int64

In [8]:
df[df.isnull().any(axis=1)]

,Unnamed: 0,id,price,bedrooms,bathrooms,sqft_living,sqft_total,floors,waterfront,view,condition,grade,built,renovated,living_area
875,875,6306400140,1095000,NaN,NaN,3064,4764,3.5,0,2,3,7,1990,0,2360
1149,1149,3421079032,75000,1.0,NaN,670,43377,1.0,0,0,3,3,1966,0,1160
3119,3119,3918400017,380000,NaN,NaN,1470,979,3.0,0,2,3,8,2006,0,1470
3467,3467,1453602309,288000,NaN,1.50,1430,1650,3.0,0,0,3,7,1999,0,1430
4868,4868,6896300380,228000,NaN,1.00,390,5900,1.0,0,0,2,4,1953,0,2170
5832,5832,5702500050,280000,1.0,NaN,600,24501,1.0,0,0,2,3,1950,0,990
6994,6994,2954400190,1295650,NaN,NaN,4810,28008,2.0,0,0,3,12,1990,0,4740
8477,8477,2569500210,339950,NaN,2.50,2290,8319,2.0,0,0,3,8,1985,0,2500
8484,8484,2310060040,240000,NaN,2.50,1810,5669,2.0,0,0,3,7,2003,0,1810
9773,9773,3374500520,355000,NaN,NaN,2460,8049,2.0,0,0,3,8,1990,0,2520
9854,9854,7849202190,235000,NaN,NaN,1470,4800,2.0,0,0,3,7,1996,0,1060
10481,10481,203100435,484000,1.0,NaN,690,23244,1.0,0,0,4,7,1948,0,1690
12653,12653,7849202299,320000,NaN,2.50,1490,7111,2.0,0,0,3,7,1999,0,1500
14423,14423,9543000205,139950,NaN,NaN,844,4269,1.0,0,0,4,7,1913,0,1380
18379,18379,1222029077,265000,NaN,0.75,384,213444,1.0,0,0,3,4,2003,0,1920
19452,19452,3980300371,142000,NaN,NaN,290,20875,1.0,0,0,1,1,1963,0,1620